feat: add bindingValidation
weweb-assets/plugin-xano-auth pull request #30
Opened 2023-08-30 17:11 UTC by AlexisJC

2023-09-05 15:11 UTC, Dams-d requested changes

2023-09-05 15:11 UTC, Dams-d commented on src/wwPlugin.js
> +            wwLib.wwNotification.open({
log the error if possible

2023-09-05 15:39 UTC, MarcFabre approved these changes

2023-09-06 08:53 UTC, Dams-d approved these changes

2023-09-07 08:39 UTC, merged